project_id = "hgxmhzswfrhvoynhasmb"

[functions.get-wallet-balance]
verify_jwt = false

[functions.verify-world-id]
verify_jwt = false

[functions.siwe-nonce]
verify_jwt = false

[functions.siwe-verify]
verify_jwt = false
