project_id = "hgxmhzswfrhvoynhasmb"

[functions.get-wallet-balance]
verify_jwt = false

[functions.get-wallet-transactions]
verify_jwt = false

[functions.porto-auth]
verify_jwt = false

[functions.notify-telegram]
verify_jwt = false

[functions.resolve-google-maps]
verify_jwt = false

[functions.resolve-luma-event]
verify_jwt = false

[functions.resolve-ens-names]
verify_jwt = false

[functions.check-donations]
verify_jwt = false

[functions.admin-ai-chat]
verify_jwt = false

[functions.notify-daily-events]
verify_jwt = false

[functions.get-solana-balance]
verify_jwt = false

[functions.telegram-debug-chat-ids]
verify_jwt = false

[functions.privy-auth]
verify_jwt = false

[functions.scrape-project-metadata]
verify_jwt = false

[functions.public-config]
verify_jwt = false

[functions.magic-auth]
verify_jwt = false
